using System;
using System.Collections.Generic;
using TaleWorlds.Core;

namespace MixedGearVisualFix
{
    public static class GloveExclusionList
    {
        // Exclude gloves by StringId only (stable, load-order-proof, modifier-proof).
        public static readonly HashSet<string> ExcludedGloveIds = new(StringComparer.OrdinalIgnoreCase)
        {
            "ao_imperial_decorated_bracers",
            "ao_imperial_decorated_bracers_b",
            "AO_durkhan_gauntlets_a",
            "AO_durkhan_gauntlets_b",
            "AR_brass_scale_gloves",
            "AR_empire_gloves_a",
            "AR_empire_gloves_b",
            "AR_empire_gloves_c",
            "AR_empire_gloves_d",
            "AR_empire_gloves_e",
            "AR_khuzait_gloves_a",
            "AR_khuzait_gloves_b",
            "AR_pict_glove_a",
            "AR_pict_glove_b",
            "AR_sturgia_gloves_a",
            "AR_sturgia_gloves_b",
            "AR_sturgia_gloves_c",
            "arm_straps_1",
            "armwraps",
            "bandit_hybrid_armor_gloves_a",
            "battania_noble_bracers",
            "battania_warlord_bracers",
            "buttoned_leather_bracers",
            "decorated_imperial_gauntlets",
            "eastern_plated_leather_vambraces",
            "eastern_wrapped_armguards",
            "el_mail_gloves_1",
            "el_mail_gloves_1ca",
            "el_mail_gloves_1ce",
            "el_mail_gloves_1hcav",
            "eoe_leathergloves1",
            "eoe_mailgloves_1",
            "eoe_mailgoves_1",
            "eoe_splinted_gloves_1",
            "guarded_armwraps",
            "guarded_padded_vambrace",
            "highland_gloves",
            "hmj_plated_mail_mittens",
            "hybrid_armor_gloves_b",
            "khuzait_heavy_armor_bracer",
            "lamellar_plate_gauntlets",
            "leather_gloves",
            "lordly_mail_mitten",
            "lordly_padded_mitten",
            "mail_mitten",
            "mail_mitten_d",
            "mail_mitten_e",
            "mail_mitten_f",
            "mail_mitten_g",
            "mail_mitten_h",
            "nord_casual_bracers",
            "northern_brass_bracers",
            "northern_plated_gloves",
            "northman_wrist_armor",
            "ota_e_sta_gloves_1",
            "ota_e_sta_legloves_1",
            "padded_mitten",
            "padded_vambrace",
            "plated_strip_gauntlets",
            "ragged_armwraps",
            "reinforced_leather_vambraces",
            "reinforced_mail_mitten",
            "reinforced_padded_mitten",
            "rough_tied_bracers",
            "roughtied_leather_bracers",
            "splinted_bracers",
            "steppe_leather_vambraces",
            "strapped_leather_bracers",
            "studded_arm_guards",
            "studded_leather_vambraces",
            "studded_vambraces",
            "ta_leatherglove_1",
            "tacky_bandit_bracer",
            "tim_2024_mail_mittens_1",
            "TV_aserai_gloves_a",
            "TV_aserai_gloves_b",
            "TV_aserai_gloves_c",
            "TV_aserai_gloves_d",
            "TV_battania_gloves_a",
            "TV_battania_gloves_b",
            "TV_battania_gloves_c",
            "TV_battania_gloves_d",
            "tv_battania_warlord_bracers",
            "TV_battania_warlord_bracers_b",
            "TV_battania_warlord_bracers_c",
            "tv_empire_plate_b",
            "TV_khuzait_gloves_a",
            "TV_khuzait_gloves_b",
            "TV_sturgia_gloves_a",
            "TV_sturgia_gloves_b",
            "TV_sturgia_gloves_c",
            "TV_sturgia_gloves_d",
            "TV_sturgia_gloves_e",
            "TV_vlandia_gloves_a",
            "TV_vlandia_gloves_b",
            "TV_vlandia_gloves_c",
            "TV_vlandia_gloves_d",
            "TV_vlandia_gloves_e",
            "TV_vlandia_gloves_f",
            "TV_vlandia_gloves_g",
            "TV_vlandia_gloves_h",
            "TV_vlandia_gloves_i",
            "woven_leather_bracers",
            "wrapped_gloves_1"
        };

        public static bool IsExcluded(ItemObject? item)
        {
            return item != null
                && !string.IsNullOrEmpty(item.StringId)
                && ExcludedGloveIds.Contains(item.StringId);
        }
    }
}